# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-12-22 17:03
from __future__ import unicode_literals

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name=b'Name')),
                ('email', models.CharField(blank=True, max_length=128, verbose_name=b'Email')),
                ('mobno', models.CharField(blank=True, max_length=32, verbose_name=b'Mob No')),
                ('college', models.CharField(blank=True, max_length=128, verbose_name=b'College Name')),
                ('ans1', models.FileField(upload_to=app.models.content_album_name)),
                ('ans2', models.FileField(upload_to=app.models.content_album_name)),
                ('ans3', models.FileField(upload_to=app.models.content_album_name)),
                ('ans4', models.FileField(upload_to=app.models.content_album_name)),
            ],
        ),
    ]
