# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-02-22 04:52
from __future__ import unicode_literals

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round1', models.IntegerField(default=0, verbose_name='Round 1 begin')),
                ('round2', models.IntegerField(default=0, verbose_name='Round 2 begin')),
                ('round3', models.IntegerField(default=0, verbose_name='Round 3 begin')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=128, verbose_name='Team Name')),
                ('password', models.CharField(max_length=128, verbose_name='Password')),
                ('teamname1', models.CharField(max_length=128, verbose_name='Team Member Name 1')),
                ('teamname2', models.CharField(max_length=128, verbose_name='Team Member Name 1')),
                ('email1', models.CharField(blank=True, max_length=128, verbose_name='Team Member 1 Email')),
                ('email2', models.CharField(blank=True, max_length=128, verbose_name='Team Member 2 Email')),
                ('mobno1', models.CharField(blank=True, max_length=32, verbose_name='Mob No 1')),
                ('mobno2', models.CharField(blank=True, max_length=32, verbose_name='Mob No 2')),
                ('ans1', models.FileField(blank=True, upload_to=app.models.content_album_name)),
                ('ans2', models.FileField(blank=True, upload_to=app.models.content_album_name)),
                ('ans3', models.FileField(blank=True, upload_to=app.models.content_album_name)),
                ('ans4', models.FileField(blank=True, upload_to=app.models.content_album_name)),
                ('ans5', models.FileField(blank=True, upload_to=app.models.content_album_name)),
                ('endround2', models.IntegerField(default=0, verbose_name='Round 1 begin')),
            ],
        ),
    ]
