# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-02-22 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='round1score',
            field=models.IntegerField(default=0, verbose_name='Round 1 score'),
        ),
        migrations.AddField(
            model_name='info',
            name='round2score',
            field=models.IntegerField(default=0, verbose_name='Round 2 score'),
        ),
    ]
