# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-02-22 05:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180222_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foradmin',
            name='round3',
            field=models.IntegerField(default=0, verbose_name='Round 2 ends'),
        ),
        migrations.AlterField(
            model_name='info',
            name='endround2',
            field=models.IntegerField(default=0, verbose_name='Round 2 end'),
        ),
        migrations.AlterField(
            model_name='info',
            name='teamname',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
